### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by gopye** [6102bitcoin/FAQ#3]
First of all, nice write up, and thanks!

Did you mean to say `doesn't leak information to anyone` ?

`Does Wasabi have a warrant canary?
The nature of Wasabi is that you shouldn't need to trust the devs or the wasabi coordinating server, as you can verify that the code *does* leak information to anyone.`

**Comment by dergigi** [comment]
Good catch! Opened a PR to fix this 👍

**Comment by 6102bitcoin** [comment]
Cheers @gopye for spotting this and raising an issue, and thanks @dergigi for issuing a pull request. Merged
