### ISSUE TITLE
Writing errors

### ISSUE THREAD

**Issue by allthegoodnamesweret4ken** [6102bitcoin/FAQ#9]
Not sure if this is the right way to do this, but just some errors I noticed while reading this (excellent!) write up.

line 86                "when" -> "with"

lines 128 & 129 "Medal" -> "Metal"

line 135              Feels like it needs another "for"...? ("generate the mnemonic FOR")
                          This would mean the word "for" would appear 3 times in the same sentence, which feels a bit much. Maybe change the first "for" to "with"?

line 180 Add laminating as a way to increase the durability of your paper backup (I keep the laminated seed in a fire retardant/resistant bag to increase the fire resistance inside a pretty basic safe). Both the bag and the stuff needed for laminating are too inexpensive not to use. See https://duckduckgo.com/?q=fire+resistant+bag&t=ffab&atb=v111-1&ia=products

I'm an absolute Github n00b, so if am supposed to do this some other way just let me know.

**Comment by 6102bitcoin** [comment]
Awesome cheers! Really appreciate it!

It's easiest next time if you make a pull request.
Basically you edit the document and request that I merge the change, I get a notification and review it and make comments and when we agree I merge the change.

https://help.github.com/en/articles/creating-a-pull-request#creating-the-pull-request

Don't worry about it for this time though 😀
